### ISSUE TITLE
Unrecognised plugin message when built with Docker

### ISSUE THREAD

**Issue by chrisbecke** [puppetlabs/vault-plugin-secrets-oauthapp#63]
## Describe the Bug

I am trying to build this plugin for inclusion in a vault image. When I attempt to enable the secrets plugin it responds with the message:

```bash
# vault secrets enable -path=oauth2 vault-plugin-secrets-oauthapp-v3.0.0-beta.3-linux-amd64
Error enabling: Error making API request.

URL: POST http://localhost:8200/v1/sys/mounts/oauth2
Code: 400. Errors:

* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

## Expected Behavior
One of
- the plugin to register
- a section in the readme detailing how to correctly build the plugin binary

## Steps to Reproduce

1. Create `docker-compose.yml` and `vault/Dockerfile`.
2. Run `docker compose build` to build the vault image.
3. Run `docker compose up -d` to run the vault image.
4. Run `docker compose exec vault sh` to access the shell in the running vault container.
5. Run `vault operator init -n 1 -t 1` to initialize the vault.
6. Run `vault operator unseal <unseal-ket>` to unseal the vault.
7. Run `vault login <token>` to set the login token.
8. Run `sha256hash /vault/plugins/vault-plugin-secrets-oauthapp-v3.0.0-beta.3-linux-amd64` to get the hash of the binary.
9. Run `vault plugin register -sha256=<hash> secret /vault/plugins/ vault-plugin-secrets-oauthapp-v3.0.0-beta.3-linux-amd64` to register the plugin.
10. Run `vault secrets enable -path=oauth2 vault-plugin-secrets-oauthapp-v3.0.0-beta.3-linux-amd64

## Files

`vault/Dockerfile`
```Dockerfile
FROM golang:1.17 AS build

# xz tools is needed for the puppetlabs build process
RUN apt-get update && apt-get install -y xz-utils
# get the plugin source
RUN git clone https://github.com/puppetlabs/vault-plugin-secrets-oauthapp.git /src
WORKDIR /src
# Use the proper build scripts
RUN make dist PLUGIN_DIST_TARGETS=dist-bin-linux-amd64
WORKDIR /src/bin
# extract the built artifact
RUN tar -xf /src/artifacts/vault-plugin-secrets-oauthapp-v3.0.0-beta.3-linux-amd64.tar.xz

FROM vault:latest AS final

COPY --from=build --chown=vault:vault /src/bin/ /vault/plugins/
```

`docker-compose.yml`
```yaml
services:
  vault:
    image: vault:oauthapp
    build:
      context: vault
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_API_ADDR: vault:8200
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true,"plugin_directory"="/vault/plugins"}}}'
    ports:
    - 8200:8200
```
